{{ if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netbox-resources-operator.serviceAccountName" . }}
  labels:
    {{- include "netbox-resources-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - spaceship.com
    resources:
      - netboxobjects
      - netboxobjects/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{ end }}
