{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "zap-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "zap-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zap-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: "metrics"
    path: {{ .Values.metrics.serviceMonitor.path }}
    interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
