{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zap-operator.serviceAccountName" . }}
  labels:
    {{- include "zap-operator.labels" . | nindent 4 }}
{{- end -}}
