apiVersion: v1
description: Metadata Reflector
name: metadata-reflector
version: 0.3.1
appVersion: 0.4.1
sources:
  - https://github.com/NCCloud/metadata-reflector
maintainers:
  - name: BonySmoke
    email: oleg.neychev@namecheap.com
