apiVersion: v2
description: A Helm chart for deploying the NetBox Resources Operator
type: application
name: netbox-resources-operator
version: 0.1.1
appVersion: 0.2.0
sources:
  - https://github.com/NCCloud/netbox-resources-operator
maintainers:
  - name: BonySmoke
    email: oleg.neychev@namecheap.com
