{{ if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard-operator.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "wireguard-operator.labels" . | nindent 4 }}
spec:
  selector:
    control-plane: controller-manager
    {{- include "wireguard-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
{{- end }}
